### ISSUE TITLE
Run multiple SMILES in one docker container

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/42#12]
In order to be able to do this, I think we will need to modify a little bit of our calculation workflow. @alesgenova can correct me if I'm wrong about any parts, but I think this is what happens:

1. Before the docker container runs, a `calculation` is posted to the `calculations` collection. This `calculation` contains a single molecule ID and most of the needed input. It is considered to be a *pending calculation*.

2. A taskflow is created using information from this `calculation`. It gets the molecule information via the molecule ID, converts it to the format needed by the docker container, and also gets the input from the `calculation`. The docker container is then ran for this single molecule.

3. When the docker container is finished, the output is written to the `calculation` and then `put` back into the database (overwriting the original `calculation` used for the input).

4. When a user tries to run a calculation in the future, it checks to see if a `calculation` already exists that used that moleculeId, input parameters, and docker image (to avoid re-running the same calculation).

In order to, in general, be able to run multiple calculations in a single docker container (such as running multiple SMILES through chemml), I think we'll need to modify this workflow. 

How? I'm not quite sure yet. But I have one proposal at least: what if we make it so that a `calculation` can have a list of molecule IDs instead of just a single molecule ID? And then the single docker container can run the same input parameters on all of the molecules in the list in one go.

Thoughts, @alesgenova, @cjh1, and @cryos?

**Comment by psavery** [comment]
Maybe another idea is to come up with an alternative method to run the docker images that bypasses the database (along with the `calculation` and `molecules` collections) and just get the output for a one-time use.

**Comment by cryos** [comment]
I think a calculation should always refer to a single molecule as it is meant to represent a single calculation that is run with a single set of results. The fact a job can run more than one calculation means that we perhaps want to more explicitly represent a job, and that job can contain more than one calculation. When searching later I want to search through calculations for each proposed calculation for matches, not the same set of calculations.

I think a job should be able to fan out to a number of calculations. As a user I don't necessarily care all that much about seeing the container job, but when running it matters quite a bit. Personally I don't even think that a job needs to have the same calculation parameters, i.e. a list of parameters and a list of geometries.

**Comment by psavery** [comment]
This issue is resolved as of [this PR](https://github.com/OpenChemistry/mongochemdeploy/pull/77) and many others.
