### ISSUE TITLE
Card and table view for molecules

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/42#8]
Previous work featured a card view:
![image](https://user-images.githubusercontent.com/42214/53657504-57245980-3c24-11e9-9ae5-c330a0fbc919.png)
and a table view:
![image](https://user-images.githubusercontent.com/42214/53657526-64d9df00-3c24-11e9-8595-5b4dc396b88b.png)
We need some equivalents for displaying results to searches, and should look at possibilities for 3D structures that summarize a sequence of results. I think we need to think about this for the single page interface, and also what we can do within Jupyter.

**Comment by cryos** [comment]
Some high level items we need to work on to get to views like this;
- [ ] Search capabilities on mass, inchi, smiles, name, etc
- [x] Creating a 2D representation on ingestion, at least for "small" molecules
- [x] Using/showing the 2D representation in the card/table view
- [x] Cards featuring the molecule name, formula, mass, code, energy, ...
- [x] Detail view that shows name/formula as a title, then 3D view, more details below the view

We can use this as a tracker, and get some of this added into the single page application/server. I would like to see listings of my molecules/calculations and the public/shared ones. Should add capabilities for starring, sharing, etc.

**Comment by cryos** [comment]
Overview of calculations consider code name, version (brackets), theory (functional if DFT), basis set, energy. Task type, i.e. energy, optimization, etc along with the SVG on the left ideally.

**Comment by cryos** [comment]
So @cjh1 and @alesgenova this has a number of the high level things I was hoping for basic search above. In addition I would like to see:
- [x] Link from calculations to their parent molecules
- [x] Listing of all calculations for a molecule
- [x] Download links for both to get XYZ, CJSON, CML, SDF data

**Comment by alesgenova** [comment]
@cryos The first two items have just been done in https://github.com/OpenChemistry/mongochemclient/pull/122

**Comment by cryos** [comment]
Don't forget my download links @alesgenova!

**Comment by alesgenova** [comment]
Download links added by https://github.com/OpenChemistry/mongochemclient/pull/128
Closing this issue!
